-- SPRING_SESSION 테이블
CREATE TABLE IF NOT EXISTS SPRING_SESSION (
    PRIMARY_ID CHAR(36) NOT NULL COMMENT '세션 고유 ID (PK)',
    SESSION_ID CHAR(36) NOT NULL COMMENT '세션 ID (고유)',
    CREATION_TIME BIGINT NOT NULL COMMENT '세션 생성 시각 (밀리초)',
    LAST_ACCESS_TIME BIGINT NOT NULL COMMENT '마지막 접근 시각 (밀리초)',
    MAX_INACTIVE_INTERVAL INT NOT NULL COMMENT '최대 비활성 시간(초)',
    EXPIRY_TIME BIGINT NOT NULL COMMENT '세션 만료 시각 (밀리초)',
    PRINCIPAL_NAME VARCHAR(200) COMMENT '세션 소유자 이름(사용자명)',
    CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID)
);

-- 인덱스
CREATE UNIQUE INDEX SPRING_SESSION_IX1 ON SPRING_SESSION (SESSION_ID);
CREATE INDEX SPRING_SESSION_IX2 ON SPRING_SESSION (EXPIRY_TIME);
CREATE INDEX SPRING_SESSION_IX3 ON SPRING_SESSION (PRINCIPAL_NAME);

-- SPRING_SESSION_ATTRIBUTES 테이블
CREATE TABLE IF NOT EXISTS SPRING_SESSION_ATTRIBUTES (
    SESSION_PRIMARY_ID CHAR(36) NOT NULL COMMENT 'SPRING_SESSION.PRIMARY_ID 참조(FK)',
    ATTRIBUTE_NAME VARCHAR(200) NOT NULL COMMENT '세션 속성 이름',
    ATTRIBUTE_BYTES BLOB NOT NULL COMMENT '세션 속성 직렬화 데이터',
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID)
        REFERENCES SPRING_SESSION(PRIMARY_ID) ON DELETE CASCADE
);
